package util;

public enum View {
	HOME,
	SEARCH,LIST_PAGING, LIST_PAGING_FOR_ADMIN,
	RECENT_REVIEW,
	ADD,ADD_REVIEW,
	RECOMMAND_MENU,
	MEMBER, MY_PAGE, LOG_IN, JOIN, FIND, FIND_ID, FIND_PW, LOG_OUT, SELECT_LOGIN,
	
	ADMIN_LOGIN, ADMIN_HOME, 
	ADMIN_REVIEW_MANAGE,
	ADMIN_REVIEW_POSTYN_MODIFY, ADMIN_REVIEW_POST_Y, ADMIN_REVIEW_BLIND,
	ADMIN_REVIEW_DETAIL,
	ADMIN_REVIEW_SEARCH, ADMIN_REVIEW_SEARCH_RESNAME, ADMIN_REVIEW_SEARCH_NICKNAME,
	ADMIN_MEMBER_MANAGE, ADMIN_MEMBER_LIST, ADMIN_MEMBER_DETAIL, ADMIN_MEMBER_DEL, ADMIN_MEMBER_DEL_DETAIL, 
	ADMIN_RES_MANAGE, 
	ADMIN_REGI_RES_MANAGE, ADMIN_REGI_RES_DETAIL, ADMIN_MODIFY_REGI_RES_DETAIL,
	ADMIN_STANDBY_RES_MANAGE, ADMIN_STANDBY_RES_DETAIL, ADMIN_MODIFY_STANDBY_RES_DETAIL,
	
	RES_SEARCH_SELECT, RES_SEARCH, RES_SEARCH_RESNAME, RES_SEARCH_CATEGORY,
	RES_LIST, RES_DETAIL, RES_DETAIL_CATEGORY, RES_ADD, RES_ADD_MODIFY,
	MENULIST_BY_RES, SERCH_RES_BY_NAME_FOR_REVIW,
	
	REVIEW, REVIEW_DETAIL, REVIEW_LIST, SEE_MENU_REVIEW_BY_MENU, SEE_MENU_REVIEW_BY_RES_N_WRITER,
	SEE_REVIEW_BY_WRITER, SEE_REVIEW_BY_RES, SEE_MENU_REVIEW_BY_MENUREVIEW, RES_BY_MENUREVIEW,
	ADD_MENUREVIEW,
	
	MY_INFO, MODIFY_MY_INFO, RESET_PW, BYEBYE, RES_ADD_ONE,
	
	BF_MAIN, BF_MAKE, RES_SEARCH_FOR_BF, BF_DETAIL

}
