package util;

public enum View {
	HOME,
	SEARCH,
	SEE_REVIEW,
	ADD,ADD_REVIEW,
	RECOMMAND_MENU,
	MEMBER, MY_PAGE, LOG_IN, JOIN, FIND, FIND_ID, FIND_PW,
	MY_INFO, MODIFY_MY_INFO, RESET_PW, BYEBYE,
  ADMIN_LOGIN

}
