package util;

public enum View {
	HOME,
	SEARCH,
	SEE_REVIEW,
	ADD,ADD_REVIEW,
	RECOMMAND_MENU,
	MEMBER, MY_PAGE, LOG_IN, JOIN, FIND, FIND_ID, FIND_PW,
	
	ADMIN_LOGIN, ADMIN_HOME, 
	ADMIN_REVIEW_CHECK,
	ADMIN_MEMBER_MANAGE,
	ADMIN_RES_MANAGE,
	
	RES_SEARCH_SELECT, RES_SEARCH, RES_SEARCH_RESNAME, RES_SEARCH_CATEGORY,
	RES_LIST, RES_DETAIL, RES_ADD,
	
	REVIEW, REVIEW_DETAIL, REVIEW_LIST
}
